"""Add staff management models

Revision ID: 50c4646b8440
Revises: d4e5f6a7b8c9
Create Date: 2026-04-30 12:24:28.328507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c4646b8440'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('worker_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_members_email'), ['email'], unique=False)

    op.create_table('staff_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_availabilities_staff_member_id'), ['staff_member_id'], unique=False)

    op.create_table('staff_service_options',
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('service_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_option_id'], ['service_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_member_id', 'service_option_id')
    )
    op.create_table('appointment_staff_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('assignment_role', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_staff_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_staff_assignments_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_staff_assignments_staff_member_id'), ['staff_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_staff_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_staff_assignments_staff_member_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_staff_assignments_appointment_id'))

    op.drop_table('appointment_staff_assignments')
    op.drop_table('staff_service_options')
    with op.batch_alter_table('staff_availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_availabilities_staff_member_id'))

    op.drop_table('staff_availabilities')
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_members_email'))

    op.drop_table('staff_members')
    # ### end Alembic commands ###
